<h1>Zadání:</h1>
<p>V tomto kurzu jste se učili s některými vybranými knihovnami. Některé sloužily pro rychlé vektorové operace, jako numpy, některé mají naprogramovány symbolické manipulace, které lze převést na numerické reprezentace (sympy), některé mají v sobě funkce pro numerickou integraci (scipy). Některé slouží i pro rychlé základní operace s čísly (numba).

Vaším úkolem je změřit potřebný čas pro vyřešení nějakého problému (např.: provést skalární součin, vypočítat určitý integrál) pomocí standardního pythonu a pomocí specializované knihovny. Toto měření proveďte alespoň pro 5 různých úloh (ne pouze jiná čísla, ale úplně jiné téma) a minimálně porovnejte rychlost jednoho modulu se standardním pythonem. Ideálně proveďte porovnání ještě s dalším modulem a snažte se, ať je kód ve standardním pythonu napsán efektivně.</p>

<h3>1. Výpočet skalárního součinu dvou velkých vektorů:</h3>
<h4>Standartní Python:</h4>

In [272]:
import time

a = [1*10**30, 2*10**30, 3*10**30]
b = [4*10**30, 5*10**30, 6*10**30]

start = time.time()
result = sum(x*y for x,y in zip(a,b))
end = time.time()

result_time = end - start
print(f"Result: {result}")
print(f"Time: {result_time}s")

Result: 32000000000000000000000000000000000000000000000000000000000000
Time: 0.0s


<h4>Numpy:</h4>

In [273]:
import numpy as np
import time

a = np.array([1*10**30, 2*10**30, 3*10**30])
b = np.array([4*10**30, 5*10**30, 6*10**30])

start = time.time()
result = np.dot(a, b)
end = time.time()

result_time = end - start
print(f"Result: {result}")
print(f"Time: {result_time}")

Result: 32000000000000000000000000000000000000000000000000000000000000
Time: 0.0


<h3>2. Výpočet určitého integrálu:</h3>
<h4>Standartní Python:</h4>

In [274]:
import time

def f(x):
    return x**2

a = 0
b = 1
n = 1000

start = time.time()
dx = (b-a)/n
integral = 0
for i in range(n):
    integral += f(a+i*dx)*dx
end = time.time()

result_time = end - start
print(f"Result: {integral}")
print(f"Time: {result_time}")

Result: 0.33283350000000034
Time: 0.0010008811950683594


<h4>Scipy:</h4>

In [275]:
import scipy as sp
import time

def f(x):
    return x**2

start = time.time()
integral = sp.integrate.quad(f, 0, 1)[0]
end = time.time()

result_time = end - start
print(f"Result: {integral}")
print(f"Time: {result_time}")

Result: 0.33333333333333337
Time: 0.0


<h3>3. Násobení dvou matic:</h3>
<h4>Standartní Python:</h4>

In [276]:
import time

A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
result = [[0, 0], [0, 0]]

start = time.time()
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
end = time.time()

result_time = end - start
print(f"Result: {result}")
print(f"Time: {result_time}s")

Result: [[19, 22], [43, 50]]
Time: 0.0s


<h4>Numpy:</h4>

In [277]:
import numpy as np
import time

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

start = time.time()
result = np.dot(A,B)
end = time.time()

result_time = end - start
print(f"Result:\n{result}")
print(f"Time: {result_time}s")

Result:
[[19 22]
 [43 50]]
Time: 0.0s


<h3>4. Výpočet determinantu matice:</h3>
<h4>Standartní Python:</h4>

In [278]:
import time

def det_3x3(m):
    [[a,b,c],[d,e,f],[g,h,i]] = m
    return a*e*i + b*f*g + c*d*h - c*e*g - b*d*i - a*f*h

matrix = [[1,2,3],[4,5,6],[7,8,9]]

start = time.time()
result = det_3x3(matrix)
end = time.time()

result_time = end - start
print(f"Result: {result}")
print(f"Time: {result_time}s")

Result: 0
Time: 0.0s


<h4>Numpy:</h4>

In [279]:
import numpy as np
import time

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

start = time.time()
result = np.linalg.det(matrix)
end = time.time()

result_time = end - start
print(f"Result: {result}")
print(f"Time: {result_time}s")

Result: 0.0
Time: 0.0s


<h3>5. Transponování matice:</h3>
<h4>Standartní Python:</h4>

In [280]:
import time

matrix = [[1,2,3],[4,5,6],[7,8,9]]

start = time.time()
result = [[row[i] for row in matrix] for i in range(len(matrix[0]))]
end = time.time()

result_time = end - start
print(f"Result: {result}")
print(f"Time: {result_time}s")

Result: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Time: 0.0009999275207519531s


<h4>Numpy:</h4>

In [281]:
import numpy as np
import time

matrix = [[1,2,3],[4,5,6],[7,8,9]]

start = time.time()
result = np.transpose(matrix)
end = time.time()

result_time = end - start
print(f"Result:\n{result}")
print(f"Time: {result_time}s")

Result:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Time: 0.0s
